試す

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,39 +1,89 @@
-jobs:
-  build_and_deploy:
-    docker:
-      - image: 'cimg/base:stable'
-    steps:
-      - checkout
-      - cloudrun/init
-      - cloudrun/build:
-          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
-      - cloudrun/deploy:
-          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
-          platform: managed
-          region: us-east1
-          service-name: example-service
-          unauthenticated: true
-      - run:
-          command: >
-            # A simple example of how a deployed managed service could be
-            verified or further tested.
+# jobs:
+#   build_and_deploy:
+#     docker:
+#       - image: 'cimg/base:stable'
+#     steps:
+#       - checkout
+#       - cloudrun/init
+#       - cloudrun/build:
+#           tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
+#       - cloudrun/deploy:
+#           image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
+#           platform: managed
+#           region: us-east1
+#           service-name: example-service
+#           unauthenticated: true
+#       - run:
+#           command: >
+#             # A simple example of how a deployed managed service could be
+#             verified or further tested.
 
-            # This step will send request our "API" and fail if there is
-            unexpected output.
+#             # This step will send request our "API" and fail if there is
+#             unexpected output.
 
-            GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
+#             GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
 
-            if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
-              echo "Result is unexpected"
-              echo 'Result: '
-              curl -s "$GCP_DEPLOY_ENDPOINT"
-              exit 1;
-            fi
-          name: Test managed deployed service.
+#             if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
+#               echo "Result is unexpected"
+#               echo 'Result: '
+#               curl -s "$GCP_DEPLOY_ENDPOINT"
+#               exit 1;
+#             fi
+#           name: Test managed deployed service.
+# orbs:
+#   cloudrun: circleci/gcp-cloud-run@1.0.2
+# version: 2.1
+# workflows:
+#   build_and_deploy_to_managed_workflow:
+#     jobs:
+#       - build_and_deploy
+
+version: 2.1 # use CircleCI 2.1
+
 orbs:
-  cloudrun: circleci/gcp-cloud-run@1.0.2
-version: 2.1
+    gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
+
+executors:
+    build:
+        docker:
+            - image: circleci/golang:1.13 #
+
+jobs:
+    # テスト時はgo1.13のdockerイメージを使ってgo testを実行
+    test-job:
+        executor:
+            name: build
+        steps:
+            - checkout
+            - run:
+                name: Run unit tests
+                command: | 
+                    cd src/api
+                    go test -v ./...
+    # デプロイ時はContainerRegistoryにビルドしたイメージを保管し、CloudRunへのデプロイを実行
+    # リポジトリのDockerfileに従ってビルドされる
+    # プロジェクトID test-project-hogehogeは変更する
+    deploy-job:
+        docker:
+            - image: 'cimg/base:stable'
+        steps:
+            - checkout
+            - run:
+                command: cd src/api
+            - gcp-cloud-run/init
+            - gcp-cloud-run/build:
+                source: ./src/api
+                tag: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/src/api:${CIRCLE_SHA1}'
+            - gcp-cloud-run/deploy:
+                image: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/src/api:${CIRCLE_SHA1}'
+                platform: managed
+                region: asia-northeast1
+                service-name: src/api
+                unauthenticated: true
+
+#テスト用ジョブ(テストのみ)とデプロイ用ジョブ(ビルド、デプロイ)に分けて実行
 workflows:
-  build_and_deploy_to_managed_workflow:
-    jobs:
-      - build_and_deploy
+    test-and-deploy:
+        jobs:
+            - test-job
+            - deploy-job
